#!/bin/bash
#Specifies the log file for grep and awk to search.
LOG_FILE='/var/log/secure'

#Looks for successful login attempts and lists them.
echo "Successful login attempts:"
grep "LOGIN ON" $LOG_FILE | awk '{print $5}' | sort | uniq -c | sort -nr
echo

#Looks for failed login attempts and lists them.
echo "Failed login attempts:"
grep "password check failed" $LOG_FILE | awk '{print $5}' | sort | uniq -c | sort -nr
